services:
  postgres:
    container_name: postgres-sql-scentquest
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: scent_quest
    volumes:
      - postgres:/data/postgres
    ports:
      - 5432:5432
    networks:
      - spring-demo
    restart: unless-stopped
  mail-dev:
    container_name: mail-dev-scentquest
    image: maildev/maildev
    ports:
      - 1080:1080
      - 1025:1025
  scentquest-api:
    container_name: scentquest-api
    image: scentquest/scentquest:1.0.3
    ports:
      - 8088:8088
    networks:
      - spring-demo
    depends_on:
      - postgres
  scentquest-ui:
    container_name: scentquest-ui
    image: scentquest/scentquest-ui:1.0.0
    ports:
      - 8080:80
    networks:
      - spring-demo
    depends_on:
      - scentquest-api
networks:
  spring-demo:
    driver: bridge

volumes:
  postgres:
    driver: local